// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: intelligence/v1/intelligence.proto

package intelligencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PredictRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    string                 `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

var File_intelligence_v1_intelligence_proto protoreflect.FileDescriptor

const file_intelligence_v1_intelligence_proto_rawDesc = "" +
	"\n" +
	"\"intelligence/v1/intelligence.proto\x12\x0fintelligence.v1\">\n" +
	"\x0ePredictRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"1\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\tR\n" +
	"prediction2c\n" +
	"\x13IntelligenceService\x12L\n" +
	"\aPredict\x12\x1f.intelligence.v1.PredictRequest\x1a .intelligence.v1.PredictResponseBwZuOlympusGCP-Intelligence/gen/v1/intelligence;intelligencev1b\x06proto3"

var (
	file_intelligence_v1_intelligence_proto_rawDescOnce sync.Once
	file_intelligence_v1_intelligence_proto_rawDescData []byte
)

func file_intelligence_v1_intelligence_proto_rawDescGZIP() []byte {
	file_intelligence_v1_intelligence_proto_rawDescOnce.Do(func() {
		file_intelligence_v1_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intelligence_v1_intelligence_proto_rawDesc), len(file_intelligence_v1_intelligence_proto_rawDesc)))
	})
	return file_intelligence_v1_intelligence_proto_rawDescData
}

var file_intelligence_v1_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_intelligence_v1_intelligence_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: intelligence.v1.PredictRequest
	(*PredictResponse)(nil), // 1: intelligence.v1.PredictResponse
}
var file_intelligence_v1_intelligence_proto_depIdxs = []int32{
	0, // 0: intelligence.v1.IntelligenceService.Predict:input_type -> intelligence.v1.PredictRequest
	1, // 1: intelligence.v1.IntelligenceService.Predict:output_type -> intelligence.v1.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_intelligence_v1_intelligence_proto_init() }
func file_intelligence_v1_intelligence_proto_init() {
	if File_intelligence_v1_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intelligence_v1_intelligence_proto_rawDesc), len(file_intelligence_v1_intelligence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intelligence_v1_intelligence_proto_goTypes,
		DependencyIndexes: file_intelligence_v1_intelligence_proto_depIdxs,
		MessageInfos:      file_intelligence_v1_intelligence_proto_msgTypes,
	}.Build()
	File_intelligence_v1_intelligence_proto = out.File
	file_intelligence_v1_intelligence_proto_goTypes = nil
	file_intelligence_v1_intelligence_proto_depIdxs = nil
}
