// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: intelligence/v1/intelligence.proto

package intelligencev1connect

import (
	v1 "OlympusGCP-Intelligence/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/intelligence/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IntelligenceServiceName is the fully-qualified name of the IntelligenceService service.
	IntelligenceServiceName = "intelligence.v1.IntelligenceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IntelligenceServicePredictProcedure is the fully-qualified name of the IntelligenceService's
	// Predict RPC.
	IntelligenceServicePredictProcedure = "/intelligence.v1.IntelligenceService/Predict"
)

// IntelligenceServiceClient is a client for the intelligence.v1.IntelligenceService service.
type IntelligenceServiceClient interface {
	Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error)
}

// NewIntelligenceServiceClient constructs a client for the intelligence.v1.IntelligenceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIntelligenceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IntelligenceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	intelligenceServiceMethods := v1.File_intelligence_v1_intelligence_proto.Services().ByName("IntelligenceService").Methods()
	return &intelligenceServiceClient{
		predict: connect.NewClient[v1.PredictRequest, v1.PredictResponse](
			httpClient,
			baseURL+IntelligenceServicePredictProcedure,
			connect.WithSchema(intelligenceServiceMethods.ByName("Predict")),
			connect.WithClientOptions(opts...),
		),
	}
}

// intelligenceServiceClient implements IntelligenceServiceClient.
type intelligenceServiceClient struct {
	predict *connect.Client[v1.PredictRequest, v1.PredictResponse]
}

// Predict calls intelligence.v1.IntelligenceService.Predict.
func (c *intelligenceServiceClient) Predict(ctx context.Context, req *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error) {
	return c.predict.CallUnary(ctx, req)
}

// IntelligenceServiceHandler is an implementation of the intelligence.v1.IntelligenceService
// service.
type IntelligenceServiceHandler interface {
	Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error)
}

// NewIntelligenceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIntelligenceServiceHandler(svc IntelligenceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	intelligenceServiceMethods := v1.File_intelligence_v1_intelligence_proto.Services().ByName("IntelligenceService").Methods()
	intelligenceServicePredictHandler := connect.NewUnaryHandler(
		IntelligenceServicePredictProcedure,
		svc.Predict,
		connect.WithSchema(intelligenceServiceMethods.ByName("Predict")),
		connect.WithHandlerOptions(opts...),
	)
	return "/intelligence.v1.IntelligenceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IntelligenceServicePredictProcedure:
			intelligenceServicePredictHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIntelligenceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIntelligenceServiceHandler struct{}

func (UnimplementedIntelligenceServiceHandler) Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("intelligence.v1.IntelligenceService.Predict is not implemented"))
}
